# name: Deploy

# on:
#   push:
#     bianches: [main]

# jobs:
#   deploy:

#     runs-on: [ubuntu-latest]

#     steps:
#     - uses: actions/checkout@v1

#     - name: Copy repository contents via scp
#       uses: appleboy/scp-action@master
#       env:
#         HOST: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#       with:
#         source: "."
#         target: "/var/www/dt"

#     - name: Executing remote command
#       uses: appleboy/ssh-action@master
#       with:
#         HOST: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#         script: ls
name: Deploy

on:
  push:
    bianches: [main]

jobs:
  deploy:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /home/devfsc/ivan.foodsafetycts.xyz/ci-cd-test
          git pull https://github.com/EdgarFSCTS/ci-cd-test.git
